// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6VXGs0hNzwwoSjBn2kfjUCZ9yQsAugU',
    appId: '1:535836066275:web:37543cc99cb9d31d8b20d6',
    messagingSenderId: '535836066275',
    projectId: 'ecotrackturmaa',
    authDomain: 'ecotrackturmaa.firebaseapp.com',
    storageBucket: 'ecotrackturmaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDIsjynUaHs9OP3t7GWbRJGcuqsyYVmJ8',
    appId: '1:535836066275:android:628ffc8f71fbbf7b8b20d6',
    messagingSenderId: '535836066275',
    projectId: 'ecotrackturmaa',
    storageBucket: 'ecotrackturmaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrgu3DMzL56BVNLEHdTDEtzaYTDvNu8-g',
    appId: '1:535836066275:ios:8dbed52b055d502b8b20d6',
    messagingSenderId: '535836066275',
    projectId: 'ecotrackturmaa',
    storageBucket: 'ecotrackturmaa.firebasestorage.app',
    iosBundleId: 'com.example.projetoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrgu3DMzL56BVNLEHdTDEtzaYTDvNu8-g',
    appId: '1:535836066275:ios:8dbed52b055d502b8b20d6',
    messagingSenderId: '535836066275',
    projectId: 'ecotrackturmaa',
    storageBucket: 'ecotrackturmaa.firebasestorage.app',
    iosBundleId: 'com.example.projetoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_6VXGs0hNzwwoSjBn2kfjUCZ9yQsAugU',
    appId: '1:535836066275:web:9e5f2fb92fe9db258b20d6',
    messagingSenderId: '535836066275',
    projectId: 'ecotrackturmaa',
    authDomain: 'ecotrackturmaa.firebaseapp.com',
    storageBucket: 'ecotrackturmaa.firebasestorage.app',
  );

}