// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBfInHW_BuMOGVhsAbvTpDeAywGKjkhcE',
    appId: '1:36791425550:web:6153a5ce57d339670aba5f',
    messagingSenderId: '36791425550',
    projectId: 'ecotrack-erika',
    authDomain: 'ecotrack-erika.firebaseapp.com',
    storageBucket: 'ecotrack-erika.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlSyWmY5LpcfBbwfBLgB2_YFa1uJY8cE',
    appId: '1:36791425550:android:9b8562d18a3610620aba5f',
    messagingSenderId: '36791425550',
    projectId: 'ecotrack-erika',
    storageBucket: 'ecotrack-erika.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ2F0KxyMwsMbGNqC7Th0ZqvVprV3C8tc',
    appId: '1:36791425550:ios:e4beecfcc2b4d5540aba5f',
    messagingSenderId: '36791425550',
    projectId: 'ecotrack-erika',
    storageBucket: 'ecotrack-erika.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ2F0KxyMwsMbGNqC7Th0ZqvVprV3C8tc',
    appId: '1:36791425550:ios:e4beecfcc2b4d5540aba5f',
    messagingSenderId: '36791425550',
    projectId: 'ecotrack-erika',
    storageBucket: 'ecotrack-erika.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBfInHW_BuMOGVhsAbvTpDeAywGKjkhcE',
    appId: '1:36791425550:web:8f0d0dea60d7d5990aba5f',
    messagingSenderId: '36791425550',
    projectId: 'ecotrack-erika',
    authDomain: 'ecotrack-erika.firebaseapp.com',
    storageBucket: 'ecotrack-erika.firebasestorage.app',
  );
}